CREATE DATABASE MARSHELL;

USE MARSHELL;

DROP TABLE IF EXISTS USERS;
CREATE TABLE IF NOT EXISTS USERS (
	ID	INT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	UNAME VARCHAR(50) NOT NULL,
	SRNAME	VARCHAR(50) NOT NULL,
	IDNUMBER VARCHAR(50) NOT NULL UNIQUE,
	MOBILE VARCHAR(20) NULL,
	REGDATE	DATETIME NOT NULL default NOW(),
	NATIONALITY	VARCHAR(10) NOT NULL DEFAULT 'NIC',
	GENDER	VARCHAR(10) NOT NULL DEFAULT 'FEMALE' ,
	LOCATION	VARCHAR(100) NULL DEFAULT 'PEARL LAGOON',
	LOGIN	VARCHAR(100) NOT NULL UNIQUE,
	PASS	VARCHAR(200) NOT NULL,
	FIRED	INT  NOT NULL DEFAULT 0,
	ROLE	VARCHAR(50) NOT NULL DEFAULT 'CASHIER',
    UNIQUE INDEX(UNAME,SRNAME,IDNUMBER,MOBILE,REGDATE,NATIONALITY,LOGIN,GENDER,LOCATION,FIRED,ROLE)
); 

DROP TABLE IF EXISTS SERVICE;
CREATE TABLE IF NOT EXISTS SERVICE (
	ID	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	DESCRIPTIONS VARCHAR(50) NOT NULL,
	PRICE FLOAT(5,2) NOT NULL ,
    CUR CHAR(3) NOT NULL DEFAULT 'NIO' CHECK(CUR IN('NIO','USD','EUR')),
    unique INDEX(ID,DESCRIPTIONS,PRICE)
); 

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE IF NOT EXISTS PRODUCT (
	ID	INT NOT NULL AUTO_INCREMENT UNIQUE,
	PRODUCTCODE	VARCHAR(50) NOT NULL,
	PRODUCTNAME	VARCHAR(50) NOT NULL,
	PRODUCTSTOCK INT NOT NULL,
	PRODUCTPRICE FLOAT(5,2) NOT NULL,
    CUR CHAR(3) NOT NULL DEFAULT 'NIO' CHECK(CUR IN('NIO','USD','EUR')),
    PRIMARY KEY(ID,PRODUCTNAME,PRODUCTCODE),
    UNIQUE INDEX(PRODUCTCODE,PRODUCTNAME,PRODUCTSTOCK,PRODUCTPRICE)
); 

DROP TABLE IF EXISTS SALES;
CREATE TABLE IF NOT EXISTS SALES (
	ID	INT NOT NULL AUTO_INCREMENT UNIQUE,
	FACTURANO VARCHAR(50) NOT NULL,
	CUSTOMERNAME VARCHAR(50) NOT NULL,
	CASHIER	VARCHAR(50) NOT NULL,
	TOTALPAY FLOAT(9,2) NOT NULL DEFAULT 0.0,
	OWING FLOAT(9,2) NOT NULL DEFAULT 0.0,
	STATUS VARCHAR(10) NOT NULL DEFAULT 'PAYED' ,
    CUR CHAR(3) NOT NULL DEFAULT 'NIO' CHECK(CUR IN('NIO','USD','EUR')),
    SALES_DATE DATETIME NOT NULL default NOW(),
	PRIMARY KEY(ID,FACTURANO,CUSTOMERNAME,CASHIER)
);

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE IF NOT EXISTS CUSTOMER  (
	ID	INT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	CNAME	VARCHAR(50) NOT NULL DEFAULT ('UNKOWN CUSTOMER ' + NOW()),
	SRNAME	VARCHAR(50)  NULL,
	IDNUMBER VARCHAR(50) NULL,
	MOBILE	VARCHAR(20) NULL DEFAULT '911',
	LOCATION VARCHAR(100) NULL,
	NATIONALITY VARCHAR(50) NULL DEFAULT 'NIC',
	GENDER VARCHAR(10) NULL DEFAULT 'FEMALE' CHECK(GENDER IN('F','M','FEMALE','MALE','FEMENINA','MASCULINO')),
	BLKCUS TINYINT NOT NULL DEFAULT 0 CHECK(BLKCUS IN(0,1)),
	OW	FLOAT(9,2) DEFAULT 0.0,
    CUR CHAR(3) DEFAULT 'NIO' CHECK(CUR IN('NIO','USD','EUR')),
    UNIQUE INDEX(CNAME,SRNAME,IDNUMBER,MOBILE,LOCATION,NATIONALITY,GENDER)
); 

INSERT INTO CUSTOMER(ID,CNAME,IDNUMBER,MOBILE,LOCATION,GENDER,BLKCUS,OW)
VALUES (0,'ANONOMO','NOT SAYING','911','unknow','male',0,0);


use marshell;


DROP TABLE IF EXISTS INVOICES;
CREATE TABLE INVOICES (
	ID	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	INVOICE	INTEGER NOT NULL,
	CUSTOMER VARCHAR(50) NULL,
	SELLER	VARCHAR(50) NOT NULL,
    IDATE DATETIME NOT NULL DEFAULT NOW(),
    STAT VARCHAR(10) NOT NULL DEFAULT 'PAYED',
    TOTAL FLOAT(9,2) NOT NULL DEFAULT 0.0,
    CUR CHAR(3) NOT NULL DEFAULT "NIO" CHECK(CUR IN("NIO","USD","EUR")) 
); 

CREATE TABLE `marshell`.`tbdate` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FACNO` VARCHAR(45) NOT NULL,
  `YEAR` TINYINT(4) NOT NULL,
  `MONTH` TINYINT(2) NOT NULL,
  `DAY` TINYINT(2) NOT NULL,
  `PROD` INT NULL COMMENT 'PRODUCT ID',
  `QNT` INT NOT NULL DEFAULT 1 COMMENT 'OUT GOIN AMOUNT',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);

 
USE MARSHELL;
 
DROP TABLE IF EXISTS CREDITS;
CREATE TABLE IF NOT EXISTS CREDITS (
	ID INT AUTO_INCREMENT NOT NULL UNIQUE,
    BARCODE VARCHAR(50) NOT NULL,
    CDATE DATETIME NOT NULL DEFAULT NOW(),
	ITEMID VARCHAR(50) NOT NULL,
    CID INT NOT NULL,
    EMPID INT NOT NULL, 
    QNT INT NOT NULL DEFAULT 1,
	OWIN FLOAT(9,2) NOT NULL,
    STAT VARCHAR(10) NOT NULL DEFAULT "OWING",
    PRIMARY KEY (ID,BARCODE,CDATE)
);

alter table credits add index(id,barcode,cdate,stat);
select * from credits;
select * from credits2; 


INSERT INTO CREDITS2 SELECT * FROM CREDITS;
DROP TABLE IF EXISTS CREDITS;
ALTER TABLE CREDITS2 RENAME CREDITS;

/* DISABLE foreign key check*/
SET FOREIGN_KEY_CHECKS=0;
SET GLOBAL FOREIGN_KEY_CHECKS=0;




/**
 ** STORED PROCEDURE START HERE
**/

USE `marshell`;
DROP procedure IF EXISTS `ADDUSERS`;
DELIMITER $$
USE `marshell`$$
CREATE  PROCEDURE `ADDUSERS`   (
IN UNAME VARCHAR(50),
IN SRNAME  VARCHAR(50),
IN MOBILE  VARCHAR(50),
 IN REGDATE  VARCHAR(50), 
 IN NACTIONALITY  VARCHAR(50),
 IN GENDER  VARCHAR(50),
 IN LOCATION  VARCHAR(50),
 IN LOGIN  VARCHAR(50),
 IN PASS  VARCHAR(50),
 IN FIRE  INT ,
 IN ROLE INT
 )
BEGIN
		INSERT INTO USERS 
		VALUES(UNAME,SRNAME,MOBILE,STR_TO_DATE(REGDATE,'%Y-%M-%D %H:%i:%s'),NACTIONALITY,GENDER,LOCATION,LOGIN,PASS,FIRED,ROLE) ;
 
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS ADDSERVICE;
DELIMITER $$
CREATE PROCEDURE ADDSERVICE(IN DESCRIPTIONS VARCHAR(50),IN PRICE FLOAT(5,2))
BEGIN
	INSERT INTO SERVICE(DESCRIPTION,PRICE) 
    VALUES(DESCRIPTIONS,PRICE)  ;
END 
DELIMITER ; 


/*  iNSER UPDATE DELETE SCRIPT*/

INSERT INTO USERS 
(UNAME,SrName,IDNumber,Mobile,RegDate,NATIONALITY,Gender,LOCATION,lOGIN,PASS,FIRED,ROLE) 
VALUES 
 ('Marshell','Marshell','626-donotknow','call',STR_TO_DATE('2019-03-03','%Y-%M-%D'),'NIC','FEMALE','P/L Gim','marshell','9RXfcqSI2TCqhOlUn24GBA==',0,'SYSTEMADMINISTRATOR'),
 ('SHEILON','GAMBOA','626-151196-1000G','89217936',STR_TO_DATE('2020-01-01','%Y-%M-%D'),'NIC','MALE','KAHKABILA','kilabone','hDpBWcECZEj/uFomyy2VbdB/TncqDbCR',0,'SYSTEMADMINISTRATOR');



INSERT INTO USERS 
(UNAME,SrName,IDNumber,Mobile,RegDate,NATIONALITY,Gender,LOCATION,lOGIN,PASS,FIRED,ROLE) 
VALUES 
('SHEILON','GAMBOA','626-151196-1000G','89217936','2020-01-01','NIC','MALE','KAHKABILA','kilabone','hDpBWcECZEj/uFomyy2VbdB/TncqDbCR',0,'SYSTEMADMINISTRATOR');

INSERT INTO USERS 
(UNAME,SrName,IDNumber,Mobile,NATIONALITY,Gender,LOCATION,lOGIN,PASS,FIRED,ROLE) 
VALUES 
 ('Marshell','Marshell','626-donotknow','call','NIC','FEMALE','P/L Gim','marshell','9RXfcqSI2TCqhOlUn24GBA==',0,'SYSTEMADMINISTRATOR');

/*query_cache_size = 16M*/
/*STR_TO_DATE(RegDate,'%Y-%M-%D')*/
SELECT * FROM USERS;
SELECT * FROM PRODUCT LIMIT 10;
SELECT * FROM SERVICE;
SELECT ID,PRODUCTCODE,PRODUCTNAME,PRODUCTSTOCK,PRODUCTPRICE,CUR FROM PRODUCT;

INSERT INTO PRODUCT VALUES(001,123,'TEST 1',900,50,'NIO');




DELIMITER $$
CREATE TRIGGER DELETEDUP 
AFTER INSERT ON PRODUCT FOR EACH ROW
BEGIN
	SELECT 
		ID,
		PRODUCTNAME,
        PRODUCTCODE
		ROW_NUMBER() OVER (PARTITION BY id, name ORDER BY id) AS row_num
	FROM t;
	DELETE FROM PRODUCT
	WHERE 
		ID IN (
		SELECT 
			ID,
            PRODUCTCODE
		FROM (
			SELECT 
				id,
				ROW_NUMBER() OVER (
					PARTITION BY email
					ORDER BY email) AS row_num
			FROM 
				PRODUCT
			
		) t
		WHERE row_num > 1
	);
END 
DELIMITER ;




/*
Speacial function in the app
*/
use marshell;
SELECT SUM(PRODUCTSTOCK) AS STOCK FROM PRODUCT;
SELECT count(*) AS AMOUNT FROM SERVICE;
SELECT SUM(AMOUT) AS AMOUNT FROM INVOICES;
SELECT * FROM INVOICES;
SELECT * FROM CUSTOMER; 
select * FROM SALES;
SELECT * FROM CREDITS;
SELECT * FROM SERVICE;

/*
CREDITS PARAMETERS
BARCODE , CDATE ,ITEMID ,CID, EMPID , QNT,OWIN , STAT 
*/
Select * from CREDITS C  JOIN CUSTOMER CS ON C.CID=CS.ID JOIN USERS U ON U.ID = C.EMPID;
/*
GET ALL DATA FROM CREDITS
*/
Select C.ID as CID,C.BARCODE AS BCODE,C.CDATE AS CDATE,C.ITEMID AS IID,C.CID AS CUSID,C.EMPID AS EMID,C.QNT AS QNT,C.OWIN AS OW,C.STAT AS STATU,CS.CNAME as CN,U.UNAME as UN,(SELECT (CONCAT_ws(" ",S.DESCRIPTIONS,P.PRODUCTCODE) )) AS ITEM,(SELECT (COALESCE(P.PRODUCTPRICE,"0")+COALESCE(S.PRICE,"0")) )AS UNITPRICE,((SELECT (COALESCE(P.PRODUCTPRICE,"0")+COALESCE(S.PRICE,"0")) )* C.QNT) AS TOTAL
FROM CREDITS as C 
LEFT OUTER JOIN PRODUCT AS P ON C.ITEMID=P.PRODUCTCODE 
LEFT OUTER JOIN  SERVICE AS S ON C.ITEMID=S.ID
INNER JOIN CUSTOMER CS ON CS.ID=C.CID 
INNER JOIN USERS U ON U.ID=C.EMPID 
WHERE C.EMPID=U.ID AND CS.ID = C.CID AND (P.PRODUCTCODE=C.ITEMID OR S.ID=C.ITEMID) OR concat(P.PRODUCTCODE,S.ID)=C.ITEMID
;
/*
SEARCH SPECIFICT ALL DATA FROM CREDITS
*/
Select P.CUR AS CUR, C.ID as CID,C.BARCODE AS BCODE,C.CDATE AS CDATE,C.ITEMID AS IID,C.CID AS CUSID,C.EMPID AS EMID,C.QNT AS QNT,C.OWIN AS OW,C.STAT AS STATU,CS.CNAME as CN,U.UNAME as UN,(SELECT (CONCAT_ws(" ",S.DESCRIPTIONS,P.PRODUCTCODE) )) AS ITEM,(SELECT (COALESCE(P.PRODUCTPRICE,"0")+COALESCE(S.PRICE,"0")) )AS UNITPRICE,((SELECT (COALESCE(P.PRODUCTPRICE,"0")+COALESCE(S.PRICE,"0")) )* C.QNT) AS TOTAL
FROM CREDITS as C 
LEFT OUTER JOIN PRODUCT AS P ON C.ITEMID=P.PRODUCTCODE 
LEFT OUTER JOIN  SERVICE AS S ON C.ITEMID=S.ID
INNER JOIN CUSTOMER CS ON CS.ID=C.CID 
INNER JOIN USERS U ON U.ID=C.EMPID 
WHERE C.EMPID=U.ID AND CS.ID = C.CID AND (P.PRODUCTCODE=C.ITEMID OR S.ID=C.ITEMID) OR concat(P.PRODUCTCODE,S.ID)=C.ITEMID 
HAVING (CONCAT(BCODE,C.CDATE,CN,UN,IID) LIKE '%" & TEXT & "%');

Select C.ID as CID,C.BARCODE AS BCODE,C.CDATE AS CDATE,C.ITEMID AS IID,C.CID AS CUSID,C.EMPID AS EMID,C.QNT AS QNT,C.OWIN AS OW,C.STAT AS STATU,CS.CNAME as CN,U.UNAME as UN,(SELECT (CONCAT_ws(" ",S.DESCRIPTIONS,P.PRODUCTCODE) )) AS ITEM,(SELECT (COALESCE(P.PRODUCTPRICE,"0")+COALESCE(S.PRICE,"0")) )AS UNITPRICE,((SELECT (COALESCE(P.PRODUCTPRICE,"0")+COALESCE(S.PRICE,"0")) )* C.QNT) AS TOTAL
FROM CREDITS as C 
LEFT OUTER JOIN PRODUCT AS P ON C.ITEMID=P.PRODUCTCODE 
LEFT OUTER JOIN  SERVICE AS S ON C.ITEMID=S.ID
INNER JOIN CUSTOMER CS ON CS.ID=C.CID 
INNER JOIN USERS U ON U.ID=C.EMPID 
WHERE C.EMPID=U.ID AND CS.ID = C.CID AND (P.PRODUCTCODE=C.ITEMID OR S.ID=C.ITEMID) OR concat(P.PRODUCTCODE,S.ID)=C.ITEMID 
HAVING (CONCAT(BCODE,C.CDATE,CN,UN,IID) LIKE '%tes1%');

Select C.ID as CID,C.BARCODE AS BCODE,C.CDATE AS CDATE,C.ITEMID AS IID,C.CID AS CUSID,C.EMPID AS EMID,C.QNT AS QNT,C.OWIN AS OW,C.STAT AS STATU,CS.CNAME as CN,U.UNAME as UN,(SELECT (CONCAT_ws(' ',S.DESCRIPTIONS,P.PRODUCTCODE) )) AS ITEM,(SELECT (COALESCE(P.PRODUCTPRICE,'0')+COALESCE(S.PRICE,'0')) )AS UNITPRICE,((SELECT (COALESCE(P.PRODUCTPRICE,'0')+COALESCE(S.PRICE,'0')) )* C.QNT) AS TOTAL FROM CREDITS as C LEFT OUTER JOIN PRODUCT AS P ON C.ITEMID=P.PRODUCTCODE LEFT OUTER JOIN  SERVICE AS S ON C.ITEMID=S.ID INNER JOIN CUSTOMER CS ON CS.ID=C.CID INNER JOIN USERS U ON U.ID=C.EMPID WHERE C.EMPID=U.ID AND CS.ID = C.CID AND (P.PRODUCTCODE=C.ITEMID OR S.ID=C.ITEMID) AND C.BARCODE = '1273236604' order by CDATE asc;

select * from credits;
select * from credits where barcode = '1273236604';



Select C.ID AS CID,C.BARCODE AS BCODE,C.CDATE AS CDATE,C.ITEMID AS IID,C.CID AS CUSID,C.EMPID AS EMID,C.QNT AS QNT,C.OWIN AS OW,C.STAT AS STATU,CS.CNAME as CN,U.UNAME as UN,(S.DESCRIPTIONS + P.PRODUCTNAME) AS ITEM,(P.PRODUCTPRICE + S.PRICE ) AS UNITPRICE,((P.PRODUCTPRICE + S.PRICE )* C.QNT) AS TOTAL FROM CREDITS as C  JOIN CUSTOMER CS ON C.CID=CS.ID JOIN USERS U ON U.ID = C.EMPID JOIN SERVICE S ON C.ITEMID = S.ID JOIN PRODUCT P ON C.ITEMID = P.PRODUCTCODE WHERE CONCAT(C.ID, C.BARCODE,C.CDATE, U.UNAME, CS.CNAME) Like '%" & text & "%';



INSERT INTO INVOICES(INVOICE,CUSTOMER,SELLER,ITEMS,AMOUT,CUR) VALUES('1234567890','2','alina','pp','7','NIO');

INSERT IGNORE INTO CREDITS(BARCODE,PID,SID,CID,EMPID,PNAME,PPRICE,SNAME,SPRICE,QNT,TOTAL,STAT) 
VALUES('test','0','2',1,1,'',0,'manr',20,6,120,'owin');



































